codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "40...95"

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no